version: '3.8'

services:
  webui:
    build:
      context: ./webui
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:4000:3000"
  webui2:
    build:
      context: ./webui
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:4001:3000"